name: PerWorldChatPlugin
version: '${project.version}'
main: plugin.perworldchatplugin.PerWorldChatPlugin
api-version: '1.20'

commands:
  pwcp:
    description: plugin basic commands.
    permission: op